# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Build Project

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Set Build Version
      run: |
        echo ::set-env name=BUILD_VERSION::$(gradle properties -q | grep "version:" | awk '{print $2}' | tr -d '[:space:]')
    - name: Test Version Code
      run: |
        echo $BUILD_VERSION
    - name: Upload JAR
      uses: actions/upload-artifact@v1
      with:
        name: 'DungeonKit-JAR'
        path:  build/libs/Dungeon-Kit-jvm
        env: $BUILD_VERSION
    - name: Upload Node Package
      uses: actions/upload-artifact@v1
      with:
        name: 'DungeonKit-JS'
        path: build/js/packages/
